# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.network "private_network", ip: "192.168.1.12"
    web.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/bionic64"
    app.vm.network "private_network", ip: "192.168.1.11"
    app.vm.network "public_network", ip: "192.168.2.10"
    app.vm.provision "shell", path: "app.sh"

  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.network "private_network", ip: "192.168.1.13"
    db.vm.provision "shell", path: "db.sh"
  end
  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/bionic64"
    client.vm.network "private_network", ip: "20.0.2.20"
    client.vm.provision "shell", path: "client.sh"
  end
end
