# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.network "private_network", ip: "192.168.0.10"
    web.vm.network "forwarded_port", guest: 80, host: 80
    web.vm.provision "shell", inline: <<-SHELL
      sudo apt-get install git
      sudo apt-get install -y apache2
      cd /var/www/html
      git clone https://github.com/caste1410/REDES
      mv /var/www/html/REDES/Proyecto_1/public/media/ /var/www/html/
      mv /var/www/html/REDES/Proyecto_1/public/hour.js /var/www/html/
      mv /var/www/html/REDES/Proyecto_1/public/index.html /var/www/html/
      mv /var/www/html/REDES/Proyecto_1/public/main.css /var/www/html/
      rm -r REDES
      echo "webserver" > /etc/hostname
      hostname -b webserver
      echo "192.168.0.20        clockserver" >> /etc/hosts
    SHELL

  end
  config.vm.define "clock" do |clock|
    clock.vm.box = "ubuntu/bionic64"
    clock.vm.network "private_network", ip: "192.168.0.20"
    clock.vm.network "forwarded_port", guest: 8080, host: 8080
    clock.vm.provision "shell", inline: <<-SHELL
      curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
      sudo apt-get install -y nodejs
      sudo apt-get install git
      mkdir server
      cd server
      git clone https://github.com/caste1410/REDES
      mv /home/vagrant/server/REDES/Proyecto_1/server/server.js /home/vagrant/server/
      rm -r REDES
      node server.js &
      echo "clockserver" > /etc/hostname
      hostname -b clockserver
      echo "192.168.0.10        webserver" >> /etc/hosts
    SHELL
  end
end